### ISSUE TITLE
Testing pypreclin at NIN

### ISSUE THREAD

**Issue by pcklink** [neurospin/pypreclin#1]
Hi people, 

Congrats on getting the pipeline out and thanks for making it all open. I am interested in comparing the results against our/my own preprocessing pipeline (https://github.com/VisionandCognition/NHP-BIDS) to see if it would make sense to change our workflow. I'll be trying some things in the upcoming days/weeks depending on available time and will report back here with anything that's unclear, won't work or required extra tweaking.

To start things off:

- there's a typo in the very first 'functional' line of your example `preproc.py` (and the notebook too). It tries to import `prepoc` instead of `preproc`, which of course doesn't work. It took me a while to not misread it as it should be and realize the 'r' was missing.
- os is not imported, but it is used
- the way the example is set up, warp may be set to False, but the arguments to do unwarping are still required by `preproc` yielding the following error: TypeError: preproc() missing 8 required positional arguments: 'delta_te', 'dwell_time', 'manufacturer', 'blip_files', 'blip_enc_dirs', 'unwarp_direction', 'phase_file', and 'magnitude_file'. I now initialize these arguments as `None`, but if unwarping is optional these arguments should probably be made obstional in pypreclin as well.
- jipdir is first specified, then overwritten with a hardcoded path (/jip/bin) 

The code then references an fslconfig python environment that doesn't exist on my system. ($FSLDIR is of course an existing environment variable, but that's not enough).

So, it currently doesn't seem incredibly straightforward to run pypreclin on another system. Perhaps I should look at the singularity image. I haven't used singularity before, but I installed it and figured out how to get into a shell on the image and link some data-folders. If I go to a python3 shell on the singularity image I can import the `pypreclin` module but if I then want to configure the paths to run `preproc` I don't know where I should find the jip folder. Your example lists `/jip/bin` but this doesn't exist. Nor do `/etc/jip`, `/opt/jip`, or `/bin/jip`. For now this is also a dead end...

Are there any superobvious things I'm missing? Have you tested running `pypreclin` outside of Neurospin or on a 'virgin' system?

**Comment by Tasserie** [comment]
Hi Chris,

We are glad you think about using pypreclin.

In fact, the codes were ready but not the exemple so we updated it https://neurospin.github.io/pypreclin/auto_gallery/preproc.html#sphx-glr-auto-gallery-preproc-py.
We also added a warm up use case in this section https://github.com/neurospin/pypreclin#install.
It will guide you through the installation and first use of pypreclin.
Note that the singularity image was created to process data on HPC.
Note the last version of pypreclin on pypi 1.0.2: https://pypi.org/project/pypreclin.

Everything was tested at NeuroSpin and outside. We are deeply interesting by your feedbacks and ideas to improve the package.

Best.
Jordy TASSERIE & Antoine GRIGIS
